import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_home_page_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__home_page_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum_features_page_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__features_page_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum_faq_page_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__faq_page_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum_header_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__header_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum_footer_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__footer_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum_site_settings_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__site_settings_v_version_status" AS ENUM('draft', 'published');
  ALTER TABLE "home_page_hero_bullets" ALTER COLUMN "text" DROP NOT NULL;
  ALTER TABLE "home_page_comparison_challenges_items" ALTER COLUMN "title" DROP NOT NULL;
  ALTER TABLE "home_page_comparison_challenges_items" ALTER COLUMN "description" DROP NOT NULL;
  ALTER TABLE "home_page_comparison_solutions_items" ALTER COLUMN "title" DROP NOT NULL;
  ALTER TABLE "home_page_comparison_solutions_items" ALTER COLUMN "description" DROP NOT NULL;
  ALTER TABLE "home_page_portal_screens" ALTER COLUMN "tab" DROP NOT NULL;
  ALTER TABLE "home_page_portal_screens" ALTER COLUMN "icon" DROP NOT NULL;
  ALTER TABLE "home_page_portal_screens" ALTER COLUMN "path" DROP NOT NULL;
  ALTER TABLE "home_page_portal_screens" ALTER COLUMN "label" DROP NOT NULL;
  ALTER TABLE "home_page_portal_screens" ALTER COLUMN "caption" DROP NOT NULL;
  ALTER TABLE "home_page_portal_screens" ALTER COLUMN "image_id" DROP NOT NULL;
  ALTER TABLE "home_page_benefits_items" ALTER COLUMN "title" DROP NOT NULL;
  ALTER TABLE "home_page_benefits_items" ALTER COLUMN "icon" DROP NOT NULL;
  ALTER TABLE "home_page_benefits_items" ALTER COLUMN "description" DROP NOT NULL;
  ALTER TABLE "home_page_benefits_items" ALTER COLUMN "highlight" DROP NOT NULL;
  ALTER TABLE "home_page_demo_steps" ALTER COLUMN "number" DROP NOT NULL;
  ALTER TABLE "home_page_demo_steps" ALTER COLUMN "title" DROP NOT NULL;
  ALTER TABLE "home_page_demo_steps" ALTER COLUMN "description" DROP NOT NULL;
  ALTER TABLE "home_page_demo_steps" ALTER COLUMN "icon" DROP NOT NULL;
  ALTER TABLE "home_page_demo_highlights" ALTER COLUMN "text" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "hero_badge" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "hero_heading" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "hero_intro" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "hero_primary_cta_label" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "hero_primary_cta_href" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "hero_secondary_cta_label" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "hero_secondary_cta_href" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "hero_image_id" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_intro_chip" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_intro_heading" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_intro_description" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_before_image_id" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_after_image_id" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_before_tab" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_after_tab" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_before_badge" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_after_badge" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_challenges_title" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_challenges_subtitle" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_solutions_title" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_solutions_subtitle" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "portal_intro_chip" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "portal_intro_heading" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "portal_intro_description" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "portal_url_prefix" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "portal_live_label" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "portal_cta_label" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "portal_cta_href" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "portal_note" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "benefits_intro_chip" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "benefits_intro_heading" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "benefits_intro_description" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "benefits_banner_eyebrow" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "benefits_banner_heading" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "benefits_banner_body" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "benefits_banner_cta_label" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "benefits_banner_cta_href" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "benefits_banner_image_id" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "demo_intro_chip" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "demo_intro_heading" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "demo_intro_description" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "demo_highlights_label" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "demo_form_title" DROP NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "demo_form_subtitle" DROP NOT NULL;
  ALTER TABLE "_home_page_v_version_hero_bullets" ALTER COLUMN "text" DROP NOT NULL;
  ALTER TABLE "_home_page_v_version_comparison_challenges_items" ALTER COLUMN "title" DROP NOT NULL;
  ALTER TABLE "_home_page_v_version_comparison_challenges_items" ALTER COLUMN "description" DROP NOT NULL;
  ALTER TABLE "_home_page_v_version_comparison_solutions_items" ALTER COLUMN "title" DROP NOT NULL;
  ALTER TABLE "_home_page_v_version_comparison_solutions_items" ALTER COLUMN "description" DROP NOT NULL;
  ALTER TABLE "_home_page_v_version_portal_screens" ALTER COLUMN "tab" DROP NOT NULL;
  ALTER TABLE "_home_page_v_version_portal_screens" ALTER COLUMN "icon" DROP NOT NULL;
  ALTER TABLE "_home_page_v_version_portal_screens" ALTER COLUMN "path" DROP NOT NULL;
  ALTER TABLE "_home_page_v_version_portal_screens" ALTER COLUMN "label" DROP NOT NULL;
  ALTER TABLE "_home_page_v_version_portal_screens" ALTER COLUMN "caption" DROP NOT NULL;
  ALTER TABLE "_home_page_v_version_portal_screens" ALTER COLUMN "image_id" DROP NOT NULL;
  ALTER TABLE "_home_page_v_version_benefits_items" ALTER COLUMN "title" DROP NOT NULL;
  ALTER TABLE "_home_page_v_version_benefits_items" ALTER COLUMN "icon" DROP NOT NULL;
  ALTER TABLE "_home_page_v_version_benefits_items" ALTER COLUMN "description" DROP NOT NULL;
  ALTER TABLE "_home_page_v_version_benefits_items" ALTER COLUMN "highlight" DROP NOT NULL;
  ALTER TABLE "_home_page_v_version_demo_steps" ALTER COLUMN "number" DROP NOT NULL;
  ALTER TABLE "_home_page_v_version_demo_steps" ALTER COLUMN "title" DROP NOT NULL;
  ALTER TABLE "_home_page_v_version_demo_steps" ALTER COLUMN "description" DROP NOT NULL;
  ALTER TABLE "_home_page_v_version_demo_steps" ALTER COLUMN "icon" DROP NOT NULL;
  ALTER TABLE "_home_page_v_version_demo_highlights" ALTER COLUMN "text" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_hero_badge" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_hero_heading" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_hero_intro" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_hero_primary_cta_label" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_hero_primary_cta_href" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_hero_secondary_cta_label" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_hero_secondary_cta_href" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_hero_image_id" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_intro_chip" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_intro_heading" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_intro_description" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_before_image_id" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_after_image_id" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_before_tab" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_after_tab" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_before_badge" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_after_badge" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_challenges_title" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_challenges_subtitle" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_solutions_title" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_solutions_subtitle" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_portal_intro_chip" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_portal_intro_heading" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_portal_intro_description" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_portal_url_prefix" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_portal_live_label" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_portal_cta_label" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_portal_cta_href" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_portal_note" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_benefits_intro_chip" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_benefits_intro_heading" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_benefits_intro_description" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_benefits_banner_eyebrow" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_benefits_banner_heading" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_benefits_banner_body" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_benefits_banner_cta_label" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_benefits_banner_cta_href" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_benefits_banner_image_id" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_demo_intro_chip" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_demo_intro_heading" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_demo_intro_description" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_demo_highlights_label" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_demo_form_title" DROP NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_demo_form_subtitle" DROP NOT NULL;
  ALTER TABLE "features_page_hardware_stats" ALTER COLUMN "value" DROP NOT NULL;
  ALTER TABLE "features_page_hardware_stats" ALTER COLUMN "label" DROP NOT NULL;
  ALTER TABLE "features_page_hardware_specs" ALTER COLUMN "title" DROP NOT NULL;
  ALTER TABLE "features_page_hardware_specs" ALTER COLUMN "icon" DROP NOT NULL;
  ALTER TABLE "features_page_hardware_specs" ALTER COLUMN "description" DROP NOT NULL;
  ALTER TABLE "features_page_hardware_specs" ALTER COLUMN "detail" DROP NOT NULL;
  ALTER TABLE "features_page_matrix_rows" ALTER COLUMN "area" DROP NOT NULL;
  ALTER TABLE "features_page_matrix_rows" ALTER COLUMN "traditional" DROP NOT NULL;
  ALTER TABLE "features_page_matrix_rows" ALTER COLUMN "carehub" DROP NOT NULL;
  ALTER TABLE "features_page_matrix_rows" ALTER COLUMN "impact" DROP NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "hardware_intro_chip" DROP NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "hardware_intro_heading" DROP NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "hardware_intro_description" DROP NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "hardware_device_name" DROP NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "hardware_model_badge" DROP NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "hardware_image_id" DROP NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "hardware_cta_label" DROP NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "matrix_intro_chip" DROP NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "matrix_intro_heading" DROP NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "matrix_intro_description" DROP NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "matrix_columns_area" DROP NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "matrix_columns_traditional" DROP NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "matrix_columns_carehub" DROP NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "matrix_columns_impact" DROP NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "meta_title" DROP NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "meta_description" DROP NOT NULL;
  ALTER TABLE "_features_page_v_version_hardware_stats" ALTER COLUMN "value" DROP NOT NULL;
  ALTER TABLE "_features_page_v_version_hardware_stats" ALTER COLUMN "label" DROP NOT NULL;
  ALTER TABLE "_features_page_v_version_hardware_specs" ALTER COLUMN "title" DROP NOT NULL;
  ALTER TABLE "_features_page_v_version_hardware_specs" ALTER COLUMN "icon" DROP NOT NULL;
  ALTER TABLE "_features_page_v_version_hardware_specs" ALTER COLUMN "description" DROP NOT NULL;
  ALTER TABLE "_features_page_v_version_hardware_specs" ALTER COLUMN "detail" DROP NOT NULL;
  ALTER TABLE "_features_page_v_version_matrix_rows" ALTER COLUMN "area" DROP NOT NULL;
  ALTER TABLE "_features_page_v_version_matrix_rows" ALTER COLUMN "traditional" DROP NOT NULL;
  ALTER TABLE "_features_page_v_version_matrix_rows" ALTER COLUMN "carehub" DROP NOT NULL;
  ALTER TABLE "_features_page_v_version_matrix_rows" ALTER COLUMN "impact" DROP NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_hardware_intro_chip" DROP NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_hardware_intro_heading" DROP NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_hardware_intro_description" DROP NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_hardware_device_name" DROP NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_hardware_model_badge" DROP NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_hardware_image_id" DROP NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_hardware_cta_label" DROP NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_matrix_intro_chip" DROP NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_matrix_intro_heading" DROP NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_matrix_intro_description" DROP NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_matrix_columns_area" DROP NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_matrix_columns_traditional" DROP NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_matrix_columns_carehub" DROP NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_matrix_columns_impact" DROP NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_meta_title" DROP NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_meta_description" DROP NOT NULL;
  ALTER TABLE "faq_page_items" ALTER COLUMN "question" DROP NOT NULL;
  ALTER TABLE "faq_page_items" ALTER COLUMN "answer" DROP NOT NULL;
  ALTER TABLE "faq_page" ALTER COLUMN "intro_chip" DROP NOT NULL;
  ALTER TABLE "faq_page" ALTER COLUMN "intro_heading" DROP NOT NULL;
  ALTER TABLE "faq_page" ALTER COLUMN "intro_description" DROP NOT NULL;
  ALTER TABLE "faq_page" ALTER COLUMN "cta_heading" DROP NOT NULL;
  ALTER TABLE "faq_page" ALTER COLUMN "cta_description" DROP NOT NULL;
  ALTER TABLE "faq_page" ALTER COLUMN "cta_button_label" DROP NOT NULL;
  ALTER TABLE "faq_page" ALTER COLUMN "cta_button_href" DROP NOT NULL;
  ALTER TABLE "faq_page" ALTER COLUMN "meta_title" DROP NOT NULL;
  ALTER TABLE "faq_page" ALTER COLUMN "meta_description" DROP NOT NULL;
  ALTER TABLE "_faq_page_v_version_items" ALTER COLUMN "question" DROP NOT NULL;
  ALTER TABLE "_faq_page_v_version_items" ALTER COLUMN "answer" DROP NOT NULL;
  ALTER TABLE "_faq_page_v" ALTER COLUMN "version_intro_chip" DROP NOT NULL;
  ALTER TABLE "_faq_page_v" ALTER COLUMN "version_intro_heading" DROP NOT NULL;
  ALTER TABLE "_faq_page_v" ALTER COLUMN "version_intro_description" DROP NOT NULL;
  ALTER TABLE "_faq_page_v" ALTER COLUMN "version_cta_heading" DROP NOT NULL;
  ALTER TABLE "_faq_page_v" ALTER COLUMN "version_cta_description" DROP NOT NULL;
  ALTER TABLE "_faq_page_v" ALTER COLUMN "version_cta_button_label" DROP NOT NULL;
  ALTER TABLE "_faq_page_v" ALTER COLUMN "version_cta_button_href" DROP NOT NULL;
  ALTER TABLE "_faq_page_v" ALTER COLUMN "version_meta_title" DROP NOT NULL;
  ALTER TABLE "_faq_page_v" ALTER COLUMN "version_meta_description" DROP NOT NULL;
  ALTER TABLE "header_nav_links" ALTER COLUMN "label" DROP NOT NULL;
  ALTER TABLE "header_nav_links" ALTER COLUMN "href" DROP NOT NULL;
  ALTER TABLE "header" ALTER COLUMN "logo_id" DROP NOT NULL;
  ALTER TABLE "header" ALTER COLUMN "cta_label" DROP NOT NULL;
  ALTER TABLE "header" ALTER COLUMN "cta_mobile_label" DROP NOT NULL;
  ALTER TABLE "header" ALTER COLUMN "cta_href" DROP NOT NULL;
  ALTER TABLE "_header_v_version_nav_links" ALTER COLUMN "label" DROP NOT NULL;
  ALTER TABLE "_header_v_version_nav_links" ALTER COLUMN "href" DROP NOT NULL;
  ALTER TABLE "_header_v" ALTER COLUMN "version_logo_id" DROP NOT NULL;
  ALTER TABLE "_header_v" ALTER COLUMN "version_cta_label" DROP NOT NULL;
  ALTER TABLE "_header_v" ALTER COLUMN "version_cta_mobile_label" DROP NOT NULL;
  ALTER TABLE "_header_v" ALTER COLUMN "version_cta_href" DROP NOT NULL;
  ALTER TABLE "footer_solutions_links" ALTER COLUMN "label" DROP NOT NULL;
  ALTER TABLE "footer_solutions_links" ALTER COLUMN "href" DROP NOT NULL;
  ALTER TABLE "footer_compliance_items" ALTER COLUMN "text" DROP NOT NULL;
  ALTER TABLE "footer_company_links" ALTER COLUMN "label" DROP NOT NULL;
  ALTER TABLE "footer_company_links" ALTER COLUMN "href" DROP NOT NULL;
  ALTER TABLE "footer_legal_links" ALTER COLUMN "label" DROP NOT NULL;
  ALTER TABLE "footer_legal_links" ALTER COLUMN "href" DROP NOT NULL;
  ALTER TABLE "footer" ALTER COLUMN "brand_name" DROP NOT NULL;
  ALTER TABLE "footer" ALTER COLUMN "brand_suffix" DROP NOT NULL;
  ALTER TABLE "footer" ALTER COLUMN "description" DROP NOT NULL;
  ALTER TABLE "footer" ALTER COLUMN "linkedin_label" DROP NOT NULL;
  ALTER TABLE "footer" ALTER COLUMN "solutions_heading" DROP NOT NULL;
  ALTER TABLE "footer" ALTER COLUMN "compliance_heading" DROP NOT NULL;
  ALTER TABLE "footer" ALTER COLUMN "company_heading" DROP NOT NULL;
  ALTER TABLE "footer" ALTER COLUMN "disclaimer" DROP NOT NULL;
  ALTER TABLE "footer" ALTER COLUMN "copyright" DROP NOT NULL;
  ALTER TABLE "_footer_v_version_solutions_links" ALTER COLUMN "label" DROP NOT NULL;
  ALTER TABLE "_footer_v_version_solutions_links" ALTER COLUMN "href" DROP NOT NULL;
  ALTER TABLE "_footer_v_version_compliance_items" ALTER COLUMN "text" DROP NOT NULL;
  ALTER TABLE "_footer_v_version_company_links" ALTER COLUMN "label" DROP NOT NULL;
  ALTER TABLE "_footer_v_version_company_links" ALTER COLUMN "href" DROP NOT NULL;
  ALTER TABLE "_footer_v_version_legal_links" ALTER COLUMN "label" DROP NOT NULL;
  ALTER TABLE "_footer_v_version_legal_links" ALTER COLUMN "href" DROP NOT NULL;
  ALTER TABLE "_footer_v" ALTER COLUMN "version_brand_name" DROP NOT NULL;
  ALTER TABLE "_footer_v" ALTER COLUMN "version_brand_suffix" DROP NOT NULL;
  ALTER TABLE "_footer_v" ALTER COLUMN "version_description" DROP NOT NULL;
  ALTER TABLE "_footer_v" ALTER COLUMN "version_linkedin_label" DROP NOT NULL;
  ALTER TABLE "_footer_v" ALTER COLUMN "version_solutions_heading" DROP NOT NULL;
  ALTER TABLE "_footer_v" ALTER COLUMN "version_compliance_heading" DROP NOT NULL;
  ALTER TABLE "_footer_v" ALTER COLUMN "version_company_heading" DROP NOT NULL;
  ALTER TABLE "_footer_v" ALTER COLUMN "version_disclaimer" DROP NOT NULL;
  ALTER TABLE "_footer_v" ALTER COLUMN "version_copyright" DROP NOT NULL;
  ALTER TABLE "site_settings" ALTER COLUMN "seo_site_name" DROP NOT NULL;
  ALTER TABLE "site_settings" ALTER COLUMN "seo_title" DROP NOT NULL;
  ALTER TABLE "site_settings" ALTER COLUMN "seo_title_template" DROP NOT NULL;
  ALTER TABLE "site_settings" ALTER COLUMN "seo_description" DROP NOT NULL;
  ALTER TABLE "site_settings" ALTER COLUMN "seo_image_id" DROP NOT NULL;
  ALTER TABLE "site_settings" ALTER COLUMN "organization_name" DROP NOT NULL;
  ALTER TABLE "site_settings" ALTER COLUMN "contact_phone_label" DROP NOT NULL;
  ALTER TABLE "site_settings" ALTER COLUMN "contact_phone_href" DROP NOT NULL;
  ALTER TABLE "site_settings" ALTER COLUMN "contact_email" DROP NOT NULL;
  ALTER TABLE "site_settings" ALTER COLUMN "contact_address" DROP NOT NULL;
  ALTER TABLE "site_settings" ALTER COLUMN "contact_linkedin_url" DROP NOT NULL;
  ALTER TABLE "_site_settings_v" ALTER COLUMN "version_seo_site_name" DROP NOT NULL;
  ALTER TABLE "_site_settings_v" ALTER COLUMN "version_seo_title" DROP NOT NULL;
  ALTER TABLE "_site_settings_v" ALTER COLUMN "version_seo_title_template" DROP NOT NULL;
  ALTER TABLE "_site_settings_v" ALTER COLUMN "version_seo_description" DROP NOT NULL;
  ALTER TABLE "_site_settings_v" ALTER COLUMN "version_seo_image_id" DROP NOT NULL;
  ALTER TABLE "_site_settings_v" ALTER COLUMN "version_organization_name" DROP NOT NULL;
  ALTER TABLE "_site_settings_v" ALTER COLUMN "version_contact_phone_label" DROP NOT NULL;
  ALTER TABLE "_site_settings_v" ALTER COLUMN "version_contact_phone_href" DROP NOT NULL;
  ALTER TABLE "_site_settings_v" ALTER COLUMN "version_contact_email" DROP NOT NULL;
  ALTER TABLE "_site_settings_v" ALTER COLUMN "version_contact_address" DROP NOT NULL;
  ALTER TABLE "_site_settings_v" ALTER COLUMN "version_contact_linkedin_url" DROP NOT NULL;
  ALTER TABLE "home_page" ADD COLUMN "_status" "enum_home_page_status" DEFAULT 'draft';
  ALTER TABLE "_home_page_v" ADD COLUMN "version__status" "enum__home_page_v_version_status" DEFAULT 'draft';
  ALTER TABLE "_home_page_v" ADD COLUMN "latest" boolean;
  ALTER TABLE "_home_page_v" ADD COLUMN "autosave" boolean;
  ALTER TABLE "features_page" ADD COLUMN "_status" "enum_features_page_status" DEFAULT 'draft';
  ALTER TABLE "_features_page_v" ADD COLUMN "version__status" "enum__features_page_v_version_status" DEFAULT 'draft';
  ALTER TABLE "_features_page_v" ADD COLUMN "latest" boolean;
  ALTER TABLE "_features_page_v" ADD COLUMN "autosave" boolean;
  ALTER TABLE "faq_page" ADD COLUMN "_status" "enum_faq_page_status" DEFAULT 'draft';
  ALTER TABLE "_faq_page_v" ADD COLUMN "version__status" "enum__faq_page_v_version_status" DEFAULT 'draft';
  ALTER TABLE "_faq_page_v" ADD COLUMN "latest" boolean;
  ALTER TABLE "_faq_page_v" ADD COLUMN "autosave" boolean;
  ALTER TABLE "header" ADD COLUMN "_status" "enum_header_status" DEFAULT 'draft';
  ALTER TABLE "_header_v" ADD COLUMN "version__status" "enum__header_v_version_status" DEFAULT 'draft';
  ALTER TABLE "_header_v" ADD COLUMN "latest" boolean;
  ALTER TABLE "_header_v" ADD COLUMN "autosave" boolean;
  ALTER TABLE "footer" ADD COLUMN "_status" "enum_footer_status" DEFAULT 'draft';
  ALTER TABLE "_footer_v" ADD COLUMN "version__status" "enum__footer_v_version_status" DEFAULT 'draft';
  ALTER TABLE "_footer_v" ADD COLUMN "latest" boolean;
  ALTER TABLE "_footer_v" ADD COLUMN "autosave" boolean;
  ALTER TABLE "site_settings" ADD COLUMN "_status" "enum_site_settings_status" DEFAULT 'draft';
  ALTER TABLE "_site_settings_v" ADD COLUMN "version__status" "enum__site_settings_v_version_status" DEFAULT 'draft';
  ALTER TABLE "_site_settings_v" ADD COLUMN "latest" boolean;
  ALTER TABLE "_site_settings_v" ADD COLUMN "autosave" boolean;
  CREATE INDEX "home_page__status_idx" ON "home_page" USING btree ("_status");
  CREATE INDEX "_home_page_v_version_version__status_idx" ON "_home_page_v" USING btree ("version__status");
  CREATE INDEX "_home_page_v_latest_idx" ON "_home_page_v" USING btree ("latest");
  CREATE INDEX "_home_page_v_autosave_idx" ON "_home_page_v" USING btree ("autosave");
  CREATE INDEX "features_page__status_idx" ON "features_page" USING btree ("_status");
  CREATE INDEX "_features_page_v_version_version__status_idx" ON "_features_page_v" USING btree ("version__status");
  CREATE INDEX "_features_page_v_latest_idx" ON "_features_page_v" USING btree ("latest");
  CREATE INDEX "_features_page_v_autosave_idx" ON "_features_page_v" USING btree ("autosave");
  CREATE INDEX "faq_page__status_idx" ON "faq_page" USING btree ("_status");
  CREATE INDEX "_faq_page_v_version_version__status_idx" ON "_faq_page_v" USING btree ("version__status");
  CREATE INDEX "_faq_page_v_latest_idx" ON "_faq_page_v" USING btree ("latest");
  CREATE INDEX "_faq_page_v_autosave_idx" ON "_faq_page_v" USING btree ("autosave");
  CREATE INDEX "header__status_idx" ON "header" USING btree ("_status");
  CREATE INDEX "_header_v_version_version__status_idx" ON "_header_v" USING btree ("version__status");
  CREATE INDEX "_header_v_latest_idx" ON "_header_v" USING btree ("latest");
  CREATE INDEX "_header_v_autosave_idx" ON "_header_v" USING btree ("autosave");
  CREATE INDEX "footer__status_idx" ON "footer" USING btree ("_status");
  CREATE INDEX "_footer_v_version_version__status_idx" ON "_footer_v" USING btree ("version__status");
  CREATE INDEX "_footer_v_latest_idx" ON "_footer_v" USING btree ("latest");
  CREATE INDEX "_footer_v_autosave_idx" ON "_footer_v" USING btree ("autosave");
  CREATE INDEX "site_settings__status_idx" ON "site_settings" USING btree ("_status");
  CREATE INDEX "_site_settings_v_version_version__status_idx" ON "_site_settings_v" USING btree ("version__status");
  CREATE INDEX "_site_settings_v_latest_idx" ON "_site_settings_v" USING btree ("latest");
  CREATE INDEX "_site_settings_v_autosave_idx" ON "_site_settings_v" USING btree ("autosave");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP INDEX "home_page__status_idx";
  DROP INDEX "_home_page_v_version_version__status_idx";
  DROP INDEX "_home_page_v_latest_idx";
  DROP INDEX "_home_page_v_autosave_idx";
  DROP INDEX "features_page__status_idx";
  DROP INDEX "_features_page_v_version_version__status_idx";
  DROP INDEX "_features_page_v_latest_idx";
  DROP INDEX "_features_page_v_autosave_idx";
  DROP INDEX "faq_page__status_idx";
  DROP INDEX "_faq_page_v_version_version__status_idx";
  DROP INDEX "_faq_page_v_latest_idx";
  DROP INDEX "_faq_page_v_autosave_idx";
  DROP INDEX "header__status_idx";
  DROP INDEX "_header_v_version_version__status_idx";
  DROP INDEX "_header_v_latest_idx";
  DROP INDEX "_header_v_autosave_idx";
  DROP INDEX "footer__status_idx";
  DROP INDEX "_footer_v_version_version__status_idx";
  DROP INDEX "_footer_v_latest_idx";
  DROP INDEX "_footer_v_autosave_idx";
  DROP INDEX "site_settings__status_idx";
  DROP INDEX "_site_settings_v_version_version__status_idx";
  DROP INDEX "_site_settings_v_latest_idx";
  DROP INDEX "_site_settings_v_autosave_idx";
  ALTER TABLE "home_page_hero_bullets" ALTER COLUMN "text" SET NOT NULL;
  ALTER TABLE "home_page_comparison_challenges_items" ALTER COLUMN "title" SET NOT NULL;
  ALTER TABLE "home_page_comparison_challenges_items" ALTER COLUMN "description" SET NOT NULL;
  ALTER TABLE "home_page_comparison_solutions_items" ALTER COLUMN "title" SET NOT NULL;
  ALTER TABLE "home_page_comparison_solutions_items" ALTER COLUMN "description" SET NOT NULL;
  ALTER TABLE "home_page_portal_screens" ALTER COLUMN "tab" SET NOT NULL;
  ALTER TABLE "home_page_portal_screens" ALTER COLUMN "icon" SET NOT NULL;
  ALTER TABLE "home_page_portal_screens" ALTER COLUMN "path" SET NOT NULL;
  ALTER TABLE "home_page_portal_screens" ALTER COLUMN "label" SET NOT NULL;
  ALTER TABLE "home_page_portal_screens" ALTER COLUMN "caption" SET NOT NULL;
  ALTER TABLE "home_page_portal_screens" ALTER COLUMN "image_id" SET NOT NULL;
  ALTER TABLE "home_page_benefits_items" ALTER COLUMN "title" SET NOT NULL;
  ALTER TABLE "home_page_benefits_items" ALTER COLUMN "icon" SET NOT NULL;
  ALTER TABLE "home_page_benefits_items" ALTER COLUMN "description" SET NOT NULL;
  ALTER TABLE "home_page_benefits_items" ALTER COLUMN "highlight" SET NOT NULL;
  ALTER TABLE "home_page_demo_steps" ALTER COLUMN "number" SET NOT NULL;
  ALTER TABLE "home_page_demo_steps" ALTER COLUMN "title" SET NOT NULL;
  ALTER TABLE "home_page_demo_steps" ALTER COLUMN "description" SET NOT NULL;
  ALTER TABLE "home_page_demo_steps" ALTER COLUMN "icon" SET NOT NULL;
  ALTER TABLE "home_page_demo_highlights" ALTER COLUMN "text" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "hero_badge" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "hero_heading" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "hero_intro" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "hero_primary_cta_label" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "hero_primary_cta_href" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "hero_secondary_cta_label" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "hero_secondary_cta_href" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "hero_image_id" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_intro_chip" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_intro_heading" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_intro_description" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_before_image_id" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_after_image_id" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_before_tab" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_after_tab" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_before_badge" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_after_badge" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_challenges_title" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_challenges_subtitle" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_solutions_title" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "comparison_solutions_subtitle" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "portal_intro_chip" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "portal_intro_heading" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "portal_intro_description" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "portal_url_prefix" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "portal_live_label" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "portal_cta_label" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "portal_cta_href" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "portal_note" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "benefits_intro_chip" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "benefits_intro_heading" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "benefits_intro_description" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "benefits_banner_eyebrow" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "benefits_banner_heading" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "benefits_banner_body" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "benefits_banner_cta_label" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "benefits_banner_cta_href" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "benefits_banner_image_id" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "demo_intro_chip" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "demo_intro_heading" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "demo_intro_description" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "demo_highlights_label" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "demo_form_title" SET NOT NULL;
  ALTER TABLE "home_page" ALTER COLUMN "demo_form_subtitle" SET NOT NULL;
  ALTER TABLE "_home_page_v_version_hero_bullets" ALTER COLUMN "text" SET NOT NULL;
  ALTER TABLE "_home_page_v_version_comparison_challenges_items" ALTER COLUMN "title" SET NOT NULL;
  ALTER TABLE "_home_page_v_version_comparison_challenges_items" ALTER COLUMN "description" SET NOT NULL;
  ALTER TABLE "_home_page_v_version_comparison_solutions_items" ALTER COLUMN "title" SET NOT NULL;
  ALTER TABLE "_home_page_v_version_comparison_solutions_items" ALTER COLUMN "description" SET NOT NULL;
  ALTER TABLE "_home_page_v_version_portal_screens" ALTER COLUMN "tab" SET NOT NULL;
  ALTER TABLE "_home_page_v_version_portal_screens" ALTER COLUMN "icon" SET NOT NULL;
  ALTER TABLE "_home_page_v_version_portal_screens" ALTER COLUMN "path" SET NOT NULL;
  ALTER TABLE "_home_page_v_version_portal_screens" ALTER COLUMN "label" SET NOT NULL;
  ALTER TABLE "_home_page_v_version_portal_screens" ALTER COLUMN "caption" SET NOT NULL;
  ALTER TABLE "_home_page_v_version_portal_screens" ALTER COLUMN "image_id" SET NOT NULL;
  ALTER TABLE "_home_page_v_version_benefits_items" ALTER COLUMN "title" SET NOT NULL;
  ALTER TABLE "_home_page_v_version_benefits_items" ALTER COLUMN "icon" SET NOT NULL;
  ALTER TABLE "_home_page_v_version_benefits_items" ALTER COLUMN "description" SET NOT NULL;
  ALTER TABLE "_home_page_v_version_benefits_items" ALTER COLUMN "highlight" SET NOT NULL;
  ALTER TABLE "_home_page_v_version_demo_steps" ALTER COLUMN "number" SET NOT NULL;
  ALTER TABLE "_home_page_v_version_demo_steps" ALTER COLUMN "title" SET NOT NULL;
  ALTER TABLE "_home_page_v_version_demo_steps" ALTER COLUMN "description" SET NOT NULL;
  ALTER TABLE "_home_page_v_version_demo_steps" ALTER COLUMN "icon" SET NOT NULL;
  ALTER TABLE "_home_page_v_version_demo_highlights" ALTER COLUMN "text" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_hero_badge" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_hero_heading" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_hero_intro" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_hero_primary_cta_label" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_hero_primary_cta_href" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_hero_secondary_cta_label" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_hero_secondary_cta_href" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_hero_image_id" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_intro_chip" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_intro_heading" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_intro_description" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_before_image_id" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_after_image_id" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_before_tab" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_after_tab" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_before_badge" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_after_badge" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_challenges_title" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_challenges_subtitle" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_solutions_title" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_comparison_solutions_subtitle" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_portal_intro_chip" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_portal_intro_heading" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_portal_intro_description" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_portal_url_prefix" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_portal_live_label" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_portal_cta_label" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_portal_cta_href" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_portal_note" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_benefits_intro_chip" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_benefits_intro_heading" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_benefits_intro_description" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_benefits_banner_eyebrow" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_benefits_banner_heading" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_benefits_banner_body" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_benefits_banner_cta_label" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_benefits_banner_cta_href" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_benefits_banner_image_id" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_demo_intro_chip" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_demo_intro_heading" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_demo_intro_description" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_demo_highlights_label" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_demo_form_title" SET NOT NULL;
  ALTER TABLE "_home_page_v" ALTER COLUMN "version_demo_form_subtitle" SET NOT NULL;
  ALTER TABLE "features_page_hardware_stats" ALTER COLUMN "value" SET NOT NULL;
  ALTER TABLE "features_page_hardware_stats" ALTER COLUMN "label" SET NOT NULL;
  ALTER TABLE "features_page_hardware_specs" ALTER COLUMN "title" SET NOT NULL;
  ALTER TABLE "features_page_hardware_specs" ALTER COLUMN "icon" SET NOT NULL;
  ALTER TABLE "features_page_hardware_specs" ALTER COLUMN "description" SET NOT NULL;
  ALTER TABLE "features_page_hardware_specs" ALTER COLUMN "detail" SET NOT NULL;
  ALTER TABLE "features_page_matrix_rows" ALTER COLUMN "area" SET NOT NULL;
  ALTER TABLE "features_page_matrix_rows" ALTER COLUMN "traditional" SET NOT NULL;
  ALTER TABLE "features_page_matrix_rows" ALTER COLUMN "carehub" SET NOT NULL;
  ALTER TABLE "features_page_matrix_rows" ALTER COLUMN "impact" SET NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "hardware_intro_chip" SET NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "hardware_intro_heading" SET NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "hardware_intro_description" SET NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "hardware_device_name" SET NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "hardware_model_badge" SET NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "hardware_image_id" SET NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "hardware_cta_label" SET NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "matrix_intro_chip" SET NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "matrix_intro_heading" SET NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "matrix_intro_description" SET NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "matrix_columns_area" SET NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "matrix_columns_traditional" SET NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "matrix_columns_carehub" SET NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "matrix_columns_impact" SET NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "meta_title" SET NOT NULL;
  ALTER TABLE "features_page" ALTER COLUMN "meta_description" SET NOT NULL;
  ALTER TABLE "_features_page_v_version_hardware_stats" ALTER COLUMN "value" SET NOT NULL;
  ALTER TABLE "_features_page_v_version_hardware_stats" ALTER COLUMN "label" SET NOT NULL;
  ALTER TABLE "_features_page_v_version_hardware_specs" ALTER COLUMN "title" SET NOT NULL;
  ALTER TABLE "_features_page_v_version_hardware_specs" ALTER COLUMN "icon" SET NOT NULL;
  ALTER TABLE "_features_page_v_version_hardware_specs" ALTER COLUMN "description" SET NOT NULL;
  ALTER TABLE "_features_page_v_version_hardware_specs" ALTER COLUMN "detail" SET NOT NULL;
  ALTER TABLE "_features_page_v_version_matrix_rows" ALTER COLUMN "area" SET NOT NULL;
  ALTER TABLE "_features_page_v_version_matrix_rows" ALTER COLUMN "traditional" SET NOT NULL;
  ALTER TABLE "_features_page_v_version_matrix_rows" ALTER COLUMN "carehub" SET NOT NULL;
  ALTER TABLE "_features_page_v_version_matrix_rows" ALTER COLUMN "impact" SET NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_hardware_intro_chip" SET NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_hardware_intro_heading" SET NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_hardware_intro_description" SET NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_hardware_device_name" SET NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_hardware_model_badge" SET NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_hardware_image_id" SET NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_hardware_cta_label" SET NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_matrix_intro_chip" SET NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_matrix_intro_heading" SET NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_matrix_intro_description" SET NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_matrix_columns_area" SET NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_matrix_columns_traditional" SET NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_matrix_columns_carehub" SET NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_matrix_columns_impact" SET NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_meta_title" SET NOT NULL;
  ALTER TABLE "_features_page_v" ALTER COLUMN "version_meta_description" SET NOT NULL;
  ALTER TABLE "faq_page_items" ALTER COLUMN "question" SET NOT NULL;
  ALTER TABLE "faq_page_items" ALTER COLUMN "answer" SET NOT NULL;
  ALTER TABLE "faq_page" ALTER COLUMN "intro_chip" SET NOT NULL;
  ALTER TABLE "faq_page" ALTER COLUMN "intro_heading" SET NOT NULL;
  ALTER TABLE "faq_page" ALTER COLUMN "intro_description" SET NOT NULL;
  ALTER TABLE "faq_page" ALTER COLUMN "cta_heading" SET NOT NULL;
  ALTER TABLE "faq_page" ALTER COLUMN "cta_description" SET NOT NULL;
  ALTER TABLE "faq_page" ALTER COLUMN "cta_button_label" SET NOT NULL;
  ALTER TABLE "faq_page" ALTER COLUMN "cta_button_href" SET NOT NULL;
  ALTER TABLE "faq_page" ALTER COLUMN "meta_title" SET NOT NULL;
  ALTER TABLE "faq_page" ALTER COLUMN "meta_description" SET NOT NULL;
  ALTER TABLE "_faq_page_v_version_items" ALTER COLUMN "question" SET NOT NULL;
  ALTER TABLE "_faq_page_v_version_items" ALTER COLUMN "answer" SET NOT NULL;
  ALTER TABLE "_faq_page_v" ALTER COLUMN "version_intro_chip" SET NOT NULL;
  ALTER TABLE "_faq_page_v" ALTER COLUMN "version_intro_heading" SET NOT NULL;
  ALTER TABLE "_faq_page_v" ALTER COLUMN "version_intro_description" SET NOT NULL;
  ALTER TABLE "_faq_page_v" ALTER COLUMN "version_cta_heading" SET NOT NULL;
  ALTER TABLE "_faq_page_v" ALTER COLUMN "version_cta_description" SET NOT NULL;
  ALTER TABLE "_faq_page_v" ALTER COLUMN "version_cta_button_label" SET NOT NULL;
  ALTER TABLE "_faq_page_v" ALTER COLUMN "version_cta_button_href" SET NOT NULL;
  ALTER TABLE "_faq_page_v" ALTER COLUMN "version_meta_title" SET NOT NULL;
  ALTER TABLE "_faq_page_v" ALTER COLUMN "version_meta_description" SET NOT NULL;
  ALTER TABLE "header_nav_links" ALTER COLUMN "label" SET NOT NULL;
  ALTER TABLE "header_nav_links" ALTER COLUMN "href" SET NOT NULL;
  ALTER TABLE "header" ALTER COLUMN "logo_id" SET NOT NULL;
  ALTER TABLE "header" ALTER COLUMN "cta_label" SET NOT NULL;
  ALTER TABLE "header" ALTER COLUMN "cta_mobile_label" SET NOT NULL;
  ALTER TABLE "header" ALTER COLUMN "cta_href" SET NOT NULL;
  ALTER TABLE "_header_v_version_nav_links" ALTER COLUMN "label" SET NOT NULL;
  ALTER TABLE "_header_v_version_nav_links" ALTER COLUMN "href" SET NOT NULL;
  ALTER TABLE "_header_v" ALTER COLUMN "version_logo_id" SET NOT NULL;
  ALTER TABLE "_header_v" ALTER COLUMN "version_cta_label" SET NOT NULL;
  ALTER TABLE "_header_v" ALTER COLUMN "version_cta_mobile_label" SET NOT NULL;
  ALTER TABLE "_header_v" ALTER COLUMN "version_cta_href" SET NOT NULL;
  ALTER TABLE "footer_solutions_links" ALTER COLUMN "label" SET NOT NULL;
  ALTER TABLE "footer_solutions_links" ALTER COLUMN "href" SET NOT NULL;
  ALTER TABLE "footer_compliance_items" ALTER COLUMN "text" SET NOT NULL;
  ALTER TABLE "footer_company_links" ALTER COLUMN "label" SET NOT NULL;
  ALTER TABLE "footer_company_links" ALTER COLUMN "href" SET NOT NULL;
  ALTER TABLE "footer_legal_links" ALTER COLUMN "label" SET NOT NULL;
  ALTER TABLE "footer_legal_links" ALTER COLUMN "href" SET NOT NULL;
  ALTER TABLE "footer" ALTER COLUMN "brand_name" SET NOT NULL;
  ALTER TABLE "footer" ALTER COLUMN "brand_suffix" SET NOT NULL;
  ALTER TABLE "footer" ALTER COLUMN "description" SET NOT NULL;
  ALTER TABLE "footer" ALTER COLUMN "linkedin_label" SET NOT NULL;
  ALTER TABLE "footer" ALTER COLUMN "solutions_heading" SET NOT NULL;
  ALTER TABLE "footer" ALTER COLUMN "compliance_heading" SET NOT NULL;
  ALTER TABLE "footer" ALTER COLUMN "company_heading" SET NOT NULL;
  ALTER TABLE "footer" ALTER COLUMN "disclaimer" SET NOT NULL;
  ALTER TABLE "footer" ALTER COLUMN "copyright" SET NOT NULL;
  ALTER TABLE "_footer_v_version_solutions_links" ALTER COLUMN "label" SET NOT NULL;
  ALTER TABLE "_footer_v_version_solutions_links" ALTER COLUMN "href" SET NOT NULL;
  ALTER TABLE "_footer_v_version_compliance_items" ALTER COLUMN "text" SET NOT NULL;
  ALTER TABLE "_footer_v_version_company_links" ALTER COLUMN "label" SET NOT NULL;
  ALTER TABLE "_footer_v_version_company_links" ALTER COLUMN "href" SET NOT NULL;
  ALTER TABLE "_footer_v_version_legal_links" ALTER COLUMN "label" SET NOT NULL;
  ALTER TABLE "_footer_v_version_legal_links" ALTER COLUMN "href" SET NOT NULL;
  ALTER TABLE "_footer_v" ALTER COLUMN "version_brand_name" SET NOT NULL;
  ALTER TABLE "_footer_v" ALTER COLUMN "version_brand_suffix" SET NOT NULL;
  ALTER TABLE "_footer_v" ALTER COLUMN "version_description" SET NOT NULL;
  ALTER TABLE "_footer_v" ALTER COLUMN "version_linkedin_label" SET NOT NULL;
  ALTER TABLE "_footer_v" ALTER COLUMN "version_solutions_heading" SET NOT NULL;
  ALTER TABLE "_footer_v" ALTER COLUMN "version_compliance_heading" SET NOT NULL;
  ALTER TABLE "_footer_v" ALTER COLUMN "version_company_heading" SET NOT NULL;
  ALTER TABLE "_footer_v" ALTER COLUMN "version_disclaimer" SET NOT NULL;
  ALTER TABLE "_footer_v" ALTER COLUMN "version_copyright" SET NOT NULL;
  ALTER TABLE "site_settings" ALTER COLUMN "seo_site_name" SET NOT NULL;
  ALTER TABLE "site_settings" ALTER COLUMN "seo_title" SET NOT NULL;
  ALTER TABLE "site_settings" ALTER COLUMN "seo_title_template" SET NOT NULL;
  ALTER TABLE "site_settings" ALTER COLUMN "seo_description" SET NOT NULL;
  ALTER TABLE "site_settings" ALTER COLUMN "seo_image_id" SET NOT NULL;
  ALTER TABLE "site_settings" ALTER COLUMN "organization_name" SET NOT NULL;
  ALTER TABLE "site_settings" ALTER COLUMN "contact_phone_label" SET NOT NULL;
  ALTER TABLE "site_settings" ALTER COLUMN "contact_phone_href" SET NOT NULL;
  ALTER TABLE "site_settings" ALTER COLUMN "contact_email" SET NOT NULL;
  ALTER TABLE "site_settings" ALTER COLUMN "contact_address" SET NOT NULL;
  ALTER TABLE "site_settings" ALTER COLUMN "contact_linkedin_url" SET NOT NULL;
  ALTER TABLE "_site_settings_v" ALTER COLUMN "version_seo_site_name" SET NOT NULL;
  ALTER TABLE "_site_settings_v" ALTER COLUMN "version_seo_title" SET NOT NULL;
  ALTER TABLE "_site_settings_v" ALTER COLUMN "version_seo_title_template" SET NOT NULL;
  ALTER TABLE "_site_settings_v" ALTER COLUMN "version_seo_description" SET NOT NULL;
  ALTER TABLE "_site_settings_v" ALTER COLUMN "version_seo_image_id" SET NOT NULL;
  ALTER TABLE "_site_settings_v" ALTER COLUMN "version_organization_name" SET NOT NULL;
  ALTER TABLE "_site_settings_v" ALTER COLUMN "version_contact_phone_label" SET NOT NULL;
  ALTER TABLE "_site_settings_v" ALTER COLUMN "version_contact_phone_href" SET NOT NULL;
  ALTER TABLE "_site_settings_v" ALTER COLUMN "version_contact_email" SET NOT NULL;
  ALTER TABLE "_site_settings_v" ALTER COLUMN "version_contact_address" SET NOT NULL;
  ALTER TABLE "_site_settings_v" ALTER COLUMN "version_contact_linkedin_url" SET NOT NULL;
  ALTER TABLE "home_page" DROP COLUMN "_status";
  ALTER TABLE "_home_page_v" DROP COLUMN "version__status";
  ALTER TABLE "_home_page_v" DROP COLUMN "latest";
  ALTER TABLE "_home_page_v" DROP COLUMN "autosave";
  ALTER TABLE "features_page" DROP COLUMN "_status";
  ALTER TABLE "_features_page_v" DROP COLUMN "version__status";
  ALTER TABLE "_features_page_v" DROP COLUMN "latest";
  ALTER TABLE "_features_page_v" DROP COLUMN "autosave";
  ALTER TABLE "faq_page" DROP COLUMN "_status";
  ALTER TABLE "_faq_page_v" DROP COLUMN "version__status";
  ALTER TABLE "_faq_page_v" DROP COLUMN "latest";
  ALTER TABLE "_faq_page_v" DROP COLUMN "autosave";
  ALTER TABLE "header" DROP COLUMN "_status";
  ALTER TABLE "_header_v" DROP COLUMN "version__status";
  ALTER TABLE "_header_v" DROP COLUMN "latest";
  ALTER TABLE "_header_v" DROP COLUMN "autosave";
  ALTER TABLE "footer" DROP COLUMN "_status";
  ALTER TABLE "_footer_v" DROP COLUMN "version__status";
  ALTER TABLE "_footer_v" DROP COLUMN "latest";
  ALTER TABLE "_footer_v" DROP COLUMN "autosave";
  ALTER TABLE "site_settings" DROP COLUMN "_status";
  ALTER TABLE "_site_settings_v" DROP COLUMN "version__status";
  ALTER TABLE "_site_settings_v" DROP COLUMN "latest";
  ALTER TABLE "_site_settings_v" DROP COLUMN "autosave";
  DROP TYPE "public"."enum_home_page_status";
  DROP TYPE "public"."enum__home_page_v_version_status";
  DROP TYPE "public"."enum_features_page_status";
  DROP TYPE "public"."enum__features_page_v_version_status";
  DROP TYPE "public"."enum_faq_page_status";
  DROP TYPE "public"."enum__faq_page_v_version_status";
  DROP TYPE "public"."enum_header_status";
  DROP TYPE "public"."enum__header_v_version_status";
  DROP TYPE "public"."enum_footer_status";
  DROP TYPE "public"."enum__footer_v_version_status";
  DROP TYPE "public"."enum_site_settings_status";
  DROP TYPE "public"."enum__site_settings_v_version_status";`)
}
