/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    redirects: Redirect;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSettings;
    'seo-settings': SeoSettings;
    tracking: Tracking;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'seo-settings': SeoSettingsSelect<false> | SeoSettingsSelect<true>;
    tracking: TrackingSelect<false> | TrackingSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Every page on the site. The page with the URL “home” is the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Used in the admin, breadcrumbs and as the default SEO title.
   */
  title: string;
  layout: (
    | HeroBlock
    | BeforeAfterBlock
    | PortalBlock
    | BenefitsBlock
    | BookDemoBlock
    | HardwareBlock
    | ComparisonTableBlock
    | FaqBlock
  )[];
  meta?: PageSeo;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * The address after the domain, e.g. “pricing” → /pricing. “home” is the home page.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  badge: string;
  /**
   * Wrap words in ==double equals== to highlight them in brand blue, or **double asterisks** to make them bold.
   */
  heading: string;
  /**
   * Wrap words in ==double equals== to highlight them in brand blue, or **double asterisks** to make them bold.
   */
  intro: string;
  bullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  primaryCta: {
    label: string;
    /**
     * e.g. /features, /#book-demo-section, https://…
     */
    href: string;
  };
  secondaryCta: {
    label: string;
    /**
     * e.g. /features, /#book-demo-section, https://…
     */
    href: string;
  };
  image: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BeforeAfterBlock".
 */
export interface BeforeAfterBlock {
  intro: {
    chip: string;
    /**
     * Wrap words in ==double equals== to highlight them in brand blue, or **double asterisks** to make them bold.
     */
    heading: string;
    description: string;
  };
  beforeImage: number | Media;
  afterImage: number | Media;
  beforeTab: string;
  afterTab: string;
  beforeBadge: string;
  afterBadge: string;
  challenges: {
    title: string;
    subtitle: string;
    items?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  solutions: {
    title: string;
    subtitle: string;
    items?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'beforeAfter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortalBlock".
 */
export interface PortalBlock {
  intro: {
    chip: string;
    /**
     * Wrap words in ==double equals== to highlight them in brand blue, or **double asterisks** to make them bold.
     */
    heading: string;
    description: string;
  };
  urlPrefix: string;
  liveLabel: string;
  screens?:
    | {
        tab: string;
        icon:
          | 'Activity'
          | 'Award'
          | 'Calendar'
          | 'CheckCircle2'
          | 'FileCheck'
          | 'FileText'
          | 'Flag'
          | 'GraduationCap'
          | 'Headphones'
          | 'HeartPulse'
          | 'Lock'
          | 'Monitor'
          | 'MonitorSmartphone'
          | 'Pill'
          | 'RefreshCw'
          | 'ScanLine'
          | 'ShieldCheck'
          | 'UserCircle'
          | 'Users'
          | 'Zap';
        /**
         * Shown after the browser bar URL prefix.
         */
        path: string;
        label: string;
        caption: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  cta: {
    label: string;
    /**
     * e.g. /features, /#book-demo-section, https://…
     */
    href: string;
  };
  note: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'portal';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitsBlock".
 */
export interface BenefitsBlock {
  intro: {
    chip: string;
    /**
     * Wrap words in ==double equals== to highlight them in brand blue, or **double asterisks** to make them bold.
     */
    heading: string;
    description: string;
  };
  items?:
    | {
        title: string;
        icon:
          | 'Activity'
          | 'Award'
          | 'Calendar'
          | 'CheckCircle2'
          | 'FileCheck'
          | 'FileText'
          | 'Flag'
          | 'GraduationCap'
          | 'Headphones'
          | 'HeartPulse'
          | 'Lock'
          | 'Monitor'
          | 'MonitorSmartphone'
          | 'Pill'
          | 'RefreshCw'
          | 'ScanLine'
          | 'ShieldCheck'
          | 'UserCircle'
          | 'Users'
          | 'Zap';
        description: string;
        highlight: string;
        id?: string | null;
      }[]
    | null;
  banner: {
    eyebrow: string;
    heading: string;
    body: string;
    cta: {
      label: string;
      /**
       * e.g. /features, /#book-demo-section, https://…
       */
      href: string;
    };
    image: number | Media;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'benefits';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BookDemoBlock".
 */
export interface BookDemoBlock {
  intro: {
    chip: string;
    /**
     * Wrap words in ==double equals== to highlight them in brand blue, or **double asterisks** to make them bold.
     */
    heading: string;
    description: string;
  };
  steps?:
    | {
        number: string;
        title: string;
        description: string;
        icon:
          | 'Activity'
          | 'Award'
          | 'Calendar'
          | 'CheckCircle2'
          | 'FileCheck'
          | 'FileText'
          | 'Flag'
          | 'GraduationCap'
          | 'Headphones'
          | 'HeartPulse'
          | 'Lock'
          | 'Monitor'
          | 'MonitorSmartphone'
          | 'Pill'
          | 'RefreshCw'
          | 'ScanLine'
          | 'ShieldCheck'
          | 'UserCircle'
          | 'Users'
          | 'Zap';
        id?: string | null;
      }[]
    | null;
  highlightsLabel: string;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  formTitle: string;
  formSubtitle: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'bookDemo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HardwareBlock".
 */
export interface HardwareBlock {
  intro: {
    chip: string;
    /**
     * Wrap words in ==double equals== to highlight them in brand blue, or **double asterisks** to make them bold.
     */
    heading: string;
    description: string;
  };
  deviceName: string;
  modelBadge: string;
  image: number | Media;
  stats?:
    | {
        value: string;
        label: string;
        highlighted?: boolean | null;
        id?: string | null;
      }[]
    | null;
  specs?:
    | {
        title: string;
        icon:
          | 'Activity'
          | 'Award'
          | 'Calendar'
          | 'CheckCircle2'
          | 'FileCheck'
          | 'FileText'
          | 'Flag'
          | 'GraduationCap'
          | 'Headphones'
          | 'HeartPulse'
          | 'Lock'
          | 'Monitor'
          | 'MonitorSmartphone'
          | 'Pill'
          | 'RefreshCw'
          | 'ScanLine'
          | 'ShieldCheck'
          | 'UserCircle'
          | 'Users'
          | 'Zap';
        description: string;
        detail: string;
        id?: string | null;
      }[]
    | null;
  ctaLabel: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hardware';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComparisonTableBlock".
 */
export interface ComparisonTableBlock {
  intro: {
    chip: string;
    /**
     * Wrap words in ==double equals== to highlight them in brand blue, or **double asterisks** to make them bold.
     */
    heading: string;
    description: string;
  };
  columns: {
    area: string;
    traditional: string;
    carehub: string;
    impact: string;
  };
  rows?:
    | {
        area: string;
        traditional: string;
        carehub: string;
        impact: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'comparisonTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  intro: {
    chip: string;
    /**
     * Wrap words in ==double equals== to highlight them in brand blue, or **double asterisks** to make them bold.
     */
    heading: string;
    description: string;
  };
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Marks up the questions above as schema.org FAQPage, so search and AI answer engines can quote them directly.
   */
  faqSchema?: boolean | null;
  cta: {
    heading: string;
    description: string;
    button: {
      label: string;
      /**
       * e.g. /features, /#book-demo-section, https://…
       */
      href: string;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageSeo".
 */
export interface PageSeo {
  title?: string | null;
  description?: string | null;
  /**
   * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
   */
  image?: (number | null) | Media;
  /**
   * By default the title template from SEO Settings is applied (e.g. “Features | CareHub”).
   */
  ignoreTitleTemplate?: boolean | null;
  /**
   * Optional. Falls back to the site-wide keywords.
   */
  keywords?: string[] | null;
  /**
   * Shown when the page is shared. Defaults to the meta title.
   */
  ogTitle?: string | null;
  /**
   * Defaults to the meta description.
   */
  ogDescription?: string | null;
  noindex?: boolean | null;
  nofollow?: boolean | null;
  /**
   * Only if this content officially lives at another URL. Defaults to this page.
   */
  canonical?: string | null;
  excludeFromSitemap?: boolean | null;
  /**
   * 0.0 – 1.0
   */
  sitemapPriority?: number | null;
  sitemapChangeFrequency?: ('always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never') | null;
  /**
   * Added to this page’s <head>, after the site-wide tags.
   */
  customMetaTags?:
    | {
        /**
         * The tag’s name attribute, e.g. "author" or "format-detection".
         */
        name: string;
        content: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Schema.org objects added to this page, e.g. a Product, Event or HowTo. WebPage, breadcrumb and FAQ data are generated automatically.
   */
  jsonLd?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * Send old or broken URLs somewhere useful. Applies to paths that don’t exist as pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Path on this site, e.g. /contact
   */
  from: string;
  /**
   * A path like /features or /#book-demo-section, or a full URL.
   */
  to: string;
  type: 'permanent' | 'temporary';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        beforeAfter?: T | BeforeAfterBlockSelect<T>;
        portal?: T | PortalBlockSelect<T>;
        benefits?: T | BenefitsBlockSelect<T>;
        bookDemo?: T | BookDemoBlockSelect<T>;
        hardware?: T | HardwareBlockSelect<T>;
        comparisonTable?: T | ComparisonTableBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
      };
  meta?: T | PageSeoSelect<T>;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  badge?: T;
  heading?: T;
  intro?: T;
  bullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BeforeAfterBlock_select".
 */
export interface BeforeAfterBlockSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        chip?: T;
        heading?: T;
        description?: T;
      };
  beforeImage?: T;
  afterImage?: T;
  beforeTab?: T;
  afterTab?: T;
  beforeBadge?: T;
  afterBadge?: T;
  challenges?:
    | T
    | {
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  solutions?:
    | T
    | {
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortalBlock_select".
 */
export interface PortalBlockSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        chip?: T;
        heading?: T;
        description?: T;
      };
  urlPrefix?: T;
  liveLabel?: T;
  screens?:
    | T
    | {
        tab?: T;
        icon?: T;
        path?: T;
        label?: T;
        caption?: T;
        image?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  note?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitsBlock_select".
 */
export interface BenefitsBlockSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        chip?: T;
        heading?: T;
        description?: T;
      };
  items?:
    | T
    | {
        title?: T;
        icon?: T;
        description?: T;
        highlight?: T;
        id?: T;
      };
  banner?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        image?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BookDemoBlock_select".
 */
export interface BookDemoBlockSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        chip?: T;
        heading?: T;
        description?: T;
      };
  steps?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  highlightsLabel?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  formTitle?: T;
  formSubtitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HardwareBlock_select".
 */
export interface HardwareBlockSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        chip?: T;
        heading?: T;
        description?: T;
      };
  deviceName?: T;
  modelBadge?: T;
  image?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        highlighted?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        title?: T;
        icon?: T;
        description?: T;
        detail?: T;
        id?: T;
      };
  ctaLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComparisonTableBlock_select".
 */
export interface ComparisonTableBlockSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        chip?: T;
        heading?: T;
        description?: T;
      };
  columns?:
    | T
    | {
        area?: T;
        traditional?: T;
        carehub?: T;
        impact?: T;
      };
  rows?:
    | T
    | {
        area?: T;
        traditional?: T;
        carehub?: T;
        impact?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        chip?: T;
        heading?: T;
        description?: T;
      };
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  faqSchema?: T;
  cta?:
    | T
    | {
        heading?: T;
        description?: T;
        button?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageSeo_select".
 */
export interface PageSeoSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  ignoreTitleTemplate?: T;
  keywords?: T;
  ogTitle?: T;
  ogDescription?: T;
  noindex?: T;
  nofollow?: T;
  canonical?: T;
  excludeFromSitemap?: T;
  sitemapPriority?: T;
  sitemapChangeFrequency?: T;
  customMetaTags?:
    | T
    | {
        name?: T;
        content?: T;
        id?: T;
      };
  jsonLd?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo: number | Media;
  navLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  cta: {
    label: string;
    mobileLabel: string;
    href: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Phone, email, address and LinkedIn come from Site Settings → Contact.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Wrap words in ==double equals== to highlight them in brand blue, or **double asterisks** to make them bold.
   */
  brandName: string;
  brandSuffix: string;
  description: string;
  linkedinLabel: string;
  solutions: {
    heading: string;
    links?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  compliance: {
    heading: string;
    items?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  company: {
    heading: string;
    links?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Wrap words in ==double equals== to highlight them in brand blue, or **double asterisks** to make them bold.
   */
  disclaimer: string;
  /**
   * Shown after “© <current year>”.
   */
  copyright: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * SEO, organization and analytics settings are under Marketing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSettings {
  id: number;
  contact: {
    phoneLabel: string;
    /**
     * What the phone link dials, starting with tel:
     */
    phoneHref: string;
    email: string;
    address: string;
    linkedinUrl: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site-wide search, social, AI-search and structured data settings. Per-page SEO is on each page’s SEO tab.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings".
 */
export interface SeoSettings {
  id: number;
  defaults: {
    siteName: string;
    /**
     * %s is replaced with the page title, e.g. “%s | CareHub”.
     */
    titleTemplate: string;
    /**
     * Used when a page has no title of its own.
     */
    title: string;
    description: string;
    /**
     * Rarely used by Google today, but some engines still read them.
     */
    keywords?: string[] | null;
    /**
     * Shown when a page is shared. 1200 × 630 px works best.
     */
    image: number | Media;
    /**
     * Open Graph locale, e.g. en_US.
     */
    locale: string;
    twitterCard: 'summary_large_image' | 'summary';
    /**
     * e.g. @carenovate
     */
    twitterHandle?: string | null;
    /**
     * Browser tab icon. Square PNG, SVG or ICO.
     */
    favicon?: (number | null) | Media;
    /**
     * Home-screen icon on iPhone/iPad. 180 × 180 PNG.
     */
    appleTouchIcon?: (number | null) | Media;
    /**
     * Browser UI colour on mobile, e.g. #0F3CD7.
     */
    themeColor?: string | null;
  };
  search: {
    /**
     * Paste only the code (the content="…" value) each tool gives you for the HTML-tag method.
     */
    verification?: {
      google?: string | null;
      bing?: string | null;
      yandex?: string | null;
      pinterest?: string | null;
    };
    /**
     * How much of the site search engines may show in results.
     */
    robots: {
      maxImagePreview: 'large' | 'standard' | 'none';
      /**
       * -1 = no limit, 0 = no snippet
       */
      maxSnippet: number;
      /**
       * -1 = no limit
       */
      maxVideoPreview: number;
    };
    /**
     * Added to every page’s <head>, e.g. other verification tags.
     */
    customMetaTags?:
      | {
          /**
           * The tag’s name attribute, e.g. "author" or "format-detection".
           */
          name: string;
          content: string;
          id?: string | null;
        }[]
      | null;
  };
  crawlers: {
    /**
     * Training crawlers: GPTBot, ClaudeBot, anthropic-ai, Google-Extended, Applebot-Extended, CCBot, Bytespider, meta-externalagent, cohere-ai. Answer/search crawlers: OAI-SearchBot, ChatGPT-User, Claude-SearchBot, Claude-User, PerplexityBot, Perplexity-User, DuckAssistBot, MistralAI-User.
     */
    aiPolicy: 'allow' | 'block-training' | 'block-all';
    rules?:
      | {
          /**
           * * for all crawlers, or a name like Googlebot.
           */
          userAgent: string;
          /**
           * Paths, e.g. /
           */
          allow?: string[] | null;
          /**
           * Paths, e.g. /admin
           */
          disallow?: string[] | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Added to the end of robots.txt as-is. The sitemap line is added automatically.
     */
    extra?: string | null;
  };
  llms?: {
    enabled?: boolean | null;
    /**
     * Leave empty to generate it automatically from your pages, FAQ, organization and contact details.
     */
    content?: string | null;
  };
  organization: {
    type: 'Organization' | 'Corporation' | 'MedicalOrganization' | 'LocalBusiness';
    name: string;
    legalName?: string | null;
    description?: string | null;
    /**
     * Defaults to the social share image.
     */
    logo?: (number | null) | Media;
    /**
     * e.g. 2021 or 2021-06-01
     */
    foundingDate?: string | null;
    /**
     * Uses the phone/email from Site Settings → Contact.
     */
    contactType?: string | null;
    /**
     * LinkedIn, Crunchbase, Wikipedia, X, YouTube… (full URLs).
     */
    sameAs?:
      | {
          url: string;
          id?: string | null;
        }[]
      | null;
    address?: {
      street?: string | null;
      locality?: string | null;
      region?: string | null;
      postalCode?: string | null;
      /**
       * e.g. US
       */
      country?: string | null;
    };
    /**
     * Extra schema.org objects for every page, e.g. your products and software. Organization and WebSite data are generated from the fields above.
     */
    additionalJsonLd?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Scripts never run in live preview, or in environments with DISABLE_ANALYTICS=true (e.g. local development).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracking".
 */
export interface Tracking {
  id: number;
  /**
   * e.g. GTM-ABC1234. Manage most other tags inside GTM.
   */
  gtmId?: string | null;
  /**
   * e.g. G-ABC123XYZ. Not needed if GA4 is set up inside GTM.
   */
  ga4Id?: string | null;
  /**
   * Other tools (Meta Pixel, LinkedIn Insight, Microsoft Clarity, Hotjar, chat widgets…). Use either a script URL or inline code.
   */
  scripts?:
    | {
        name: string;
        enabled?: boolean | null;
        strategy: 'afterInteractive' | 'lazyOnload' | 'beforeInteractive';
        src?: string | null;
        /**
         * JavaScript only, without <script> tags.
         */
        code?: string | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        mobileLabel?: T;
        href?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brandName?: T;
  brandSuffix?: T;
  description?: T;
  linkedinLabel?: T;
  solutions?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  compliance?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  company?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  disclaimer?: T;
  copyright?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  contact?:
    | T
    | {
        phoneLabel?: T;
        phoneHref?: T;
        email?: T;
        address?: T;
        linkedinUrl?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings_select".
 */
export interface SeoSettingsSelect<T extends boolean = true> {
  defaults?:
    | T
    | {
        siteName?: T;
        titleTemplate?: T;
        title?: T;
        description?: T;
        keywords?: T;
        image?: T;
        locale?: T;
        twitterCard?: T;
        twitterHandle?: T;
        favicon?: T;
        appleTouchIcon?: T;
        themeColor?: T;
      };
  search?:
    | T
    | {
        verification?:
          | T
          | {
              google?: T;
              bing?: T;
              yandex?: T;
              pinterest?: T;
            };
        robots?:
          | T
          | {
              maxImagePreview?: T;
              maxSnippet?: T;
              maxVideoPreview?: T;
            };
        customMetaTags?:
          | T
          | {
              name?: T;
              content?: T;
              id?: T;
            };
      };
  crawlers?:
    | T
    | {
        aiPolicy?: T;
        rules?:
          | T
          | {
              userAgent?: T;
              allow?: T;
              disallow?: T;
              id?: T;
            };
        extra?: T;
      };
  llms?:
    | T
    | {
        enabled?: T;
        content?: T;
      };
  organization?:
    | T
    | {
        type?: T;
        name?: T;
        legalName?: T;
        description?: T;
        logo?: T;
        foundingDate?: T;
        contactType?: T;
        sameAs?:
          | T
          | {
              url?: T;
              id?: T;
            };
        address?:
          | T
          | {
              street?: T;
              locality?: T;
              region?: T;
              postalCode?: T;
              country?: T;
            };
        additionalJsonLd?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracking_select".
 */
export interface TrackingSelect<T extends boolean = true> {
  gtmId?: T;
  ga4Id?: T;
  scripts?:
    | T
    | {
        name?: T;
        enabled?: T;
        strategy?: T;
        src?: T;
        code?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}